// remap jQuery to $
(function($){})(window.jQuery);

/*
* Handles the news slider on the homepage
*/
var newsSlider = {

	slider : $(".news-slider .flexslider"),

	init: function() {

		this.slider.flexslider({
		    namespace: "flex-",             //{NEW} String: Prefix string attached to the class of every element generated by the plugin
			selector: ".slides > li",       //{NEW} Selector: Must match a simple pattern. '{container} > {slide}' -- Ignore pattern at your own peril
			animation: "fade",              //String: Select your animation type, "fade" or "slide"
			easing: "swing",               //{NEW} String: Determines the easing method used in jQuery transitions. jQuery easing plugin is supported!
			direction: "horizontal",        //String: Select the sliding direction, "horizontal" or "vertical"
			reverse: false,                 //{NEW} Boolean: Reverse the animation direction
			animationLoop: true,             //Boolean: Should the animation loop? If false, directionNav will received "disable" classes at either end
			smoothHeight: false,            //{NEW} Boolean: Allow height of the slider to animate smoothly in horizontal mode
			startAt: 0,                     //Integer: The slide that the slider should start on. Array notation (0 = first slide)
			slideshow: true,                //Boolean: Animate slider automatically
			slideshowSpeed: 7000,           //Integer: Set the speed of the slideshow cycling, in milliseconds
			animationSpeed: 700,            //Integer: Set the speed of animations, in milliseconds
			initDelay: 0,                   //{NEW} Integer: Set an initialization delay, in milliseconds
			randomize: false               //Boolean: Randomize slide order
		  });
	}

}


/*
* Handles the smooth scrolling back to the top when link is clicked
*/
var smoothScroll = {

	anchor : $(".back-to-top"),

	init: function(){


		/* Scroll to anchor target on click */
		this.anchor.on("click", function(e){
			e.preventDefault();
			$('html, body').animate({
		        scrollTop: $( $(this).attr('href') ).offset().top
		    }, 500);
		});



	}
}

var events = {
	/*
	* Event Single pages arnt associated under either 'upcoming' or 'past' events so using
	* JS to update title.
	*/
	init: function(){
		var $eventHeader = $('#event-header'),
			fullDate = new Date(),
			//Convert date to same format as event date
			twoDigitDate = fullDate.getDate()+"";if(twoDigitDate.length==1) twoDigitDate="0" +twoDigitDate,
			twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1),
			todayDate =  fullDate.getFullYear() + twoDigitMonth + twoDigitDate;


		if($eventHeader.length) {
			// Pull the event data (on data attribute in post)
			var eventDate = $eventHeader.data('event-date');

			// Update Event title based on comparison of dates
			if (eventDate >= todayDate) {
				$eventHeader.html("Upcoming events");
			} else {
				$eventHeader.html("Past events");
			}

		}

	}

}

/*
* To support archives on custom post type a plugin was needed - but it doesnt add active classes
* to the side nav when an archive year is chosen.  This does that,
*/
var archiveHighlight = {

	init: function(){

		var $archiveTitle = $("#archive-title"),
			$archiveMenu = $("#news-archive-menu");

		if($archiveTitle.length) {
			var archiveYear = $archiveTitle.data('year'),
				$archiveYearsList = $archiveMenu.find("li");

			// Loop through each archive year and compare - add active class if match.
			$archiveYearsList.each(function(index) {
				var archiveListYear = $(this).find("a").html();
				if (archiveYear == archiveListYear ) {
					$(this).addClass('current_page_item');
				}
			});
		}
	}
}


$(document).ready(function (){
	newsSlider.init();
	smoothScroll.init();
	events.init();
	archiveHighlight.init();
});
